### ISSUE TITLE
Timing of code release

### ISSUE THREAD

**Issue by Sawersvy** [Brickzhuantou/CalibDepth#1]
Hello, I would like to ask when your code will be released, thank you very much !

**Comment by Brickzhuantou** [comment]
> Hello, I would like to ask when your code will be released, thank you very much !

Apologies for the delay. I will try to organize the code and release it around September.

**Comment by Sawersvy** [comment]
Is the IL_base branch ready to use? Thank you very much!

**Comment by Brickzhuantou** [comment]
> 

The code has been merged into the main branch, thanks for your support.

**Comment by Sawersvy** [comment]
Hi, since I read your ReadMe and you mentioned that we can refer to CalibNet to download the dataset, can I just follow the script provided by CalibNet to download it? Thank you very much!

**Comment by Brickzhuantou** [comment]
> 
I downloaded the data directly from the official website. You can try using the CalibNet script. Just make sure the final data format is the same as mentioned in the readme.
