### ISSUE TITLE
> 使用你提供的预训练权重，在测试的时候，得到MAE R: 6.6372，MAE rr: 6.6702，MAE pp: 6.6965，MAE yy: 6.5674，MAE t: 0.165894，MAE x: 0.167431，MAE y: 0.164024，MAE z: 0.166228，怎么与论文中的差别这么大

### ISSUE THREAD

**Issue by zzq123zz** [Brickzhuantou/CalibDepth#10]
> 使用你提供的预训练权重，在测试的时候，得到MAE R: 6.6372，MAE rr: 6.6702，MAE pp: 6.6965，MAE yy: 6.5674，MAE t: 0.165894，MAE x: 0.167431，MAE y: 0.164024，MAE z: 0.166228，怎么与论文中的差别这么大
![t](https://github.com/Brickzhuantou/CalibDepth/assets/48545414/587fda38-cc3e-4110-862c-24887cdf6313)
这是我这边本地用预训练模型在test.txt对应的KITTI数据中推理得到的结果；论文中给出了不同的初始扰动范围和训练测试集划分方式，需要按照论文给出的方式重新训练推理后可以复现结果

_Originally posted by @Brickzhuantou in https://github.com/Brickzhuantou/CalibDepth/issues/7#issuecomment-1785594587_

**Comment by zzq123zz** [comment]
你这些数据中旋转和平移的单位是度和cm吗

**Comment by Brickzhuantou** [comment]
> 你这些数据中旋转和平移的单位是度和cm吗

度和m
