### ISSUE TITLE
不同的模型对比

### ISSUE THREAD

**Issue by zzq123zz** [Brickzhuantou/CalibDepth#12]
你好，我想问一下，当使用你的网络模型和不同的网络模型进行对比的时候，只需要按照论文当中的数据集划分方式和扰动范围进行设置就可以吗，不需要改动数据的处理方式吗？

**Comment by Brickzhuantou** [comment]
是的

> 你好，我想问一下，当使用你的网络模型和不同的网络模型进行对比的时候，只需要按照论文当中的数据集划分方式和扰动范围进行设置就可以吗，不需要改动数据的处理方式吗？
