### ISSUE TITLE
数据集的问题

### ISSUE THREAD

**Issue by zzq123zz** [Brickzhuantou/CalibDepth#14]
你好，我想问一下，在CalibNet 当中，作者说他从09_26当中生成了24000对数据进行训练，6000对数据进行测试，但是09_26当中一共就15000对数据左右，那么他指的是加入扰动之后得到的数据吗？还有就是测试集当中的6000对数据是不是可以和训练集当中的24000对数据有重复的，因为他们加入的扰动是随机生成的。

**Comment by Brickzhuantou** [comment]
> 你好，我想问一下，在CalibNet 当中，作者说他从09_26当中生成了24000对数据进行训练，6000对数据进行测试，但是09_26当中一共就15000对数据左右，那么他指的是加入扰动之后得到的数据吗？还有就是测试集当中的6000对数据是不是可以和训练集当中的24000对数据有重复的，因为他们加入的扰动是随机生成的。

CalibNet原文也表述的不是很清晰；
第一个问题应该是加完扰动的数据基础上进行的划分；
第二个问题的话，我不太确定，个人认为他论文给的数值指标是在9-30序列上测试的，或者你可以基于我的框架复现他的网络结构进行相同数据集划分下的对比实验；

**Comment by zzq123zz** [comment]
我现在想的是从09_26当中选择12000对数据，然后乘以2，得到24000对训练数据，对剩下的3000对数据乘以2 得到6000对测试数据，不知道可不可以呢？
