### ISSUE TITLE
mkl-fft==1.3.0问题

### ISSUE THREAD

**Issue by yulongg1** [Brickzhuantou/CalibDepth#17]
你好，我在配置环境的过程中发现，mkl-fft在python==3.6.13的情况下是安装不了1.3.0版本的，python3.6版本只能安装mkl-fft的1.0.0.17, 1.0.2, 1.0.6版本，我想问一下这个问题该怎么解决？谢谢！

**Comment by Brickzhuantou** [comment]
> 你好，我在配置环境的过程中发现，mkl-fft在python==3.6.13的情况下是安装不了1.3.0版本的，python3.6版本只能安装mkl-fft的1.0.0.17, 1.0.2, 1.0.6版本，我想问一下这个问题该怎么解决？谢谢！

试试跳过这个包的安装或者安装你列举的1.0版本，这个包可能对本项目影响不大
