### ISSUE TITLE
关于lstm

### ISSUE THREAD

**Issue by Caozihan1064** [Brickzhuantou/CalibDepth#20]
您在论文中，引入了lstm网络，但是在train.py中，您加载得并不是时序得数据，而是在训练加载数据时，训练集通过shuffle=True打乱了数据集得顺序。而lstm在不是时序得数据中，是否很难起到作用吧，为什么还要引入lstm？，您是否 应该引入时间戳数据？期待您得解答。

**Comment by Brickzhuantou** [comment]
1. 本论文确实是在单帧的配置下进行的实验，文中的LSTM主要用于标定动作序列的解码，类似于轨迹生成任务中的使用，并不是为了做时序特征的关联；
2. 引入时序信息确实有可能带来更好的标定效果，可以参考CalibRCNN，或许更符合您的需求。
