### ISSUE TITLE
Hi, when will the model for test be released?  

### ISSUE THREAD

**Issue by hadonga** [Brickzhuantou/CalibDepth#3]
Your work is excellent and impressive. I will cite your paper in my current work, but before that I would like to practically conduct the performance comparison between your proposed work and ours.  

Of course, the given source code is in good shape for training, but I believe it would be more convenient and accurate to cite your work if you could upload your trained model.

Thanks in advance.

**Comment by Brickzhuantou** [comment]
https://drive.google.com/file/d/1WQX5RBw7njS-1WIDn4ro67h2gmnVZjCJ/view?usp=sharing
This is the model trained with the data in train.txt. Thanks for your support.
