### ISSUE TITLE
train.py

### ISSUE THREAD

**Issue by zzq123zz** [Brickzhuantou/CalibDepth#4]
Why did I report this error: RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)', how to solve it?

**Comment by Brickzhuantou** [comment]
> Why did I report this error: RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)', how to solve it?

I have not encountered your problem. I guess there may be a problem with the data format or the cuda environment.
