### ISSUE TITLE
问题关于pip install requirement.txt

### ISSUE THREAD

**Issue by cchester25** [Brickzhuantou/CalibDepth#5]
您好，感谢您的出色工作。我遇到了一些问题在部署您的代码时，上述命令似乎有些问题，它应该是pip3 install -r requirements.txt 。此外，requirements.txt中的第20行 出现错误：ERROR: Could not install packages due to an OSError: [Errno 2] 没有那个文件或目录: '/tmp/build/80754af9/dataclasses_1614363715916/work'  请问如何修复这个问题？

**Comment by Brickzhuantou** [comment]
> 您好，感谢您的出色工作。我遇到了一些问题在部署您的代码时，上述命令似乎有些问题，它应该是pip3 install -r requirements.txt 。此外，requirements.txt中的第20行 出现错误：ERROR: Could not install packages due to an OSError: [Errno 2] 没有那个文件或目录: '/tmp/build/80754af9/dataclasses_1614363715916/work' 请问如何修复这个问题？

感谢关注，您可以尝试将该行删除先安装其它模块，然后再单独用pip安装dataclasses模块

**Comment by cchester25** [comment]
> > 您好，感谢您的出色工作。我遇到了一些问题在部署您的代码时，上述命令似乎有些问题，它应该是pip3 install -r requirements.txt 。此外，requirements.txt中的第20行 出现错误：ERROR: Could not install packages due to an OSError: [Errno 2] 没有那个文件或目录: '/tmp/build/80754af9/dataclasses_1614363715916/work' 请问如何修复这个问题？
> 
> 感谢关注，您可以尝试将该行删除先安装其它模块，然后再单独用pip安装dataclasses模块

请问requirements.txt中带有 “@ file:xxx”的依赖，对应具体什么版本呢

**Comment by Brickzhuantou** [comment]
> > > 您好，感谢您的出色工作。我遇到了一些问题在部署您的代码时，上述命令似乎有些问题，它应该是pip3 install -r requirements.txt 。此外，requirements.txt中的第20行 出现错误：ERROR: Could not install packages due to an OSError: [Errno 2] 没有那个文件或目录: '/tmp/build/80754af9/dataclasses_1614363715916/work' 请问如何修复这个问题？
> > 
> > 
> > 感谢关注，您可以尝试将该行删除先安装其它模块，然后再单独用pip安装dataclasses模块
> 
> 请问requirements.txt中带有 “@ file:xxx”的依赖，对应具体什么版本呢

dataclasses               0.8
mathutils                 2.78    
numpy                     1.19.1   
six                       1.16.0  
typing_extensions         4.1.1
