### ISSUE TITLE
关于 test.py 

### ISSUE THREAD

**Issue by cchester25** [Brickzhuantou/CalibDepth#6]
您好,我在运行test.py时, 出现 "FileNotFoundError: No weights found at /home/ubuntu/CODE/Calib/CalibDepth/CalibDepth/weights_lstm/raw_1.zip. Download pretrained weights or run training first." 请问能否提供预训练权重呢?,还是说需要重新训练么

**Comment by Brickzhuantou** [comment]
https://github.com/Brickzhuantou/CalibDepth/issues/3
issue-3这里给出了预训练模型
