### ISSUE TITLE
test.py

### ISSUE THREAD

**Issue by zzq123zz** [Brickzhuantou/CalibDepth#7]
使用你提供的预训练权重，在测试的时候，得到MAE R: 6.6372，MAE rr: 6.6702，MAE pp: 6.6965，MAE yy: 6.5674，MAE t: 0.165894，MAE x: 0.167431，MAE y: 0.164024，MAE z: 0.166228，怎么与论文中的差别这么大

**Comment by Brickzhuantou** [comment]
> 使用你提供的预训练权重，在测试的时候，得到MAE R: 6.6372，MAE rr: 6.6702，MAE pp: 6.6965，MAE yy: 6.5674，MAE t: 0.165894，MAE x: 0.167431，MAE y: 0.164024，MAE z: 0.166228，怎么与论文中的差别这么大
![t](https://github.com/Brickzhuantou/CalibDepth/assets/48545414/587fda38-cc3e-4110-862c-24887cdf6313)
这是我这边本地用预训练模型在test.txt对应的KITTI数据中推理得到的结果；论文中给出了不同的初始扰动范围和训练测试集划分方式，需要按照论文给出的方式重新训练推理后可以复现结果

**Comment by zzq123zz** [comment]
那这样的话，数据集加载部分的代码得进行修改呀，我见你公布的代码中只是加载了train.txt和test.txt中的数据，那您能否分享一下对应不同数据集的数据加载的代码呢？



---- 回复的原邮件 ----
| 发件人 | zhuantou ***@***.***> |
| 日期 | 2023年10月31日 00:33 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [Brickzhuantou/CalibDepth] test.py (Issue #7) |

使用你提供的预训练权重，在测试的时候，得到MAE R: 6.6372，MAE rr: 6.6702，MAE pp: 6.6965，MAE yy: 6.5674，MAE t: 0.165894，MAE x: 0.167431，MAE y: 0.164024，MAE z: 0.166228，怎么与论文中的差别这么大

这是我这边本地用预训练模型在test.txt对应的KITTI数据中推理得到的结果；论文中给出了不同的初始扰动范围和训练测试集划分方式，需要按照论文给出的方式重新训练推理后可以复现结果

**Comment by zzq123zz** [comment]
你这个测试集中的数据有些是在训练集当中出现过，当我将测试集的数据换成09_30后，用你提供的预训练权重测试得到的结果怎么与论文中的T1栏结果相差的较多呢
